### ISSUE TITLE
Unity 2020 LTS with IL2CPP: RPCs with INetworkPlayer parameter cause IL2CPP generation to fail

### ISSUE THREAD

**Issue by SoftwareGuy** [MirageNet/Mirage#1020]
**Describe the bug**
This is just for record of an issue discussed in private chat where if you use a function with Unity 2020 like one of the following with a `INetworkPlayer player` parameter, when you go to compile a IL2CPP build, the IL2CPP compiler will catch fire with an error about casting something to something incorrectly.

```
[ClientRpc]
private void ThisWillCatchFire(INetworkPlayer player, bool mirageIsAwesome) {
  if(mirageIsAwesome == false)
    throw new Exception("Seriously?!");
  // ...
}
```

Editor is fine but build with IL2CPP and you'll see smoke.

**Repro project**
Refer to private chat notes.

**To Reproduce**
Refer to private chat notes.

**Expected behavior**
IL2CPP shouldn't be dumb and cast the wrong thing to the wrong thing.

**Screenshots**
Refer to private chat notes.

**Additional context**
Refer to private chat notes.

**Comment by James-Frowen** [comment]
Should be fixed up https://github.com/MirageNet/Mirage/pull/1021

**Comment by SoftwareGuy** [comment]
Perfect. Another bug solved.
