### ISSUE TITLE
Increasing Mirage.Serialization.StringExtensions.MaxStringLength does not actually work

### ISSUE THREAD

**Issue by jbarnoin** [MirageNet/Mirage#1109]
The documentation for StringExtensions.MaxStringLength states that the default of 1300 "Can be changed by user if they need to", and MaxStringLength is public to that effect.

Unfortunately, this does not work. Setting MaxStringLength externally does not recreate the stringBuffer byte array, and that one is private so it cannot be worked around without modifying the library.

It would be great to have a Property setter or function that correctly updates the byte buffer size.

As an aside, it would also be nice to clarify that MaxStringLength is not a length in characters, but in bytes (maybe MaxStringByteLength) as this can differ when encoding a Unicode string and we got bit by that. In particular it cannot be compared with string.Length to check if the string will fit.

Thanks !

**Comment by James-Frowen** [comment]
I've changed it to a property that also resizes the array.

I have also added extra methods that let people use different encoding if needed.

I've added a doc comment saying that this is the size in bytes after encoding. depending on the use case, it might be possible to use `Encoding.GetByteCount(string)` to check the size.
