### ISSUE TITLE
Network Scene Manager

### ISSUE THREAD

**Issue by JamesMcGhee** [MirageNet/Mirage#586]
**Please explain the suggested feature in detail.**
No need for a Network Scene Manager ... your current implamentaiton assumes NetworkSceneManager is not null

**How exactly does this keep you from releasing your game right now?**
In all of our projects we manage our scenes our selves and have multiple scenes loaded at any given time. Our scenes do not nessisarly translate to a physical location in the game world, each game's specific scene architecutre is unique ... this is not something that a networking tool needs to bother with and especially shouldn't be requiring to have set up.

**Can you suggest a possible solution?**
Dont assume a NetworkSceneManager is present, if its null assume the dev is handling scene management on its own

**Additional context**

**Comment by dragonslaya84** [comment]
While you may not want to as a power user end users who just want to pick up and go and code and expect this to just work out of the box without them needing to do any lifting is kind of expected. If you need to do your own thing you can override the NetworkSceneManager stuff and do things like a power user would. 

The idea is to have things in place so end users can just install and start coding and things are taken care for them without having to read through massive documents. Now if you are a power user I can see the need to do your own thing and that should just have things be able to override or like you said if its null then just expect end user's are doing there own thing.

**Comment by uweenukr** [comment]
The reason it's forced currently is based on the idea that Unity cannot run a game without a scene of some sort. Even if it's a default unnamed scene. So if the engine forces scenes to exist. Why not just make peace with it.

I was looking at it today and wondering if the object layer could just spawn everything if a NetworkSceneManager is not present.

So let's see if we can brain storm a better solution that still let's 80% of users get up and running in under 5 minutes without much fiddling around.

**Comment by JamesMcGhee** [comment]
I have nothing against scenes existing, I have a lot against being forced to use a scene as a 'level' or 'room' or 'page' or 'area' etc. 
A scene is simply a colleciton of GameObjects and a bit of extra data light lighting that Unity can load up on deman where build index 0 is loaded up on start. That isn't a complicated concepts and we support young/new Unity devs all the time that are using scenes in novel ways so its not a 'power user' only feature.

I dont know what all funcitonality you have tied up into Network Scene Manager

I can say though that its always been iritating that UNET like networking solutions attempt to be a scene manager. Originaly making the assumption that its a single scene set up e.g. only 1 scene active at a time with a fixed offline and online.

Thinking about it I couldn't really come up with a good reason why the network should care what the structure or state of scenes are in a game. 
At first I was thinking well the network needs to make sure the spawned objects are being applied to X scene ... however that isn't true. The network wont care where the objects are in the higherarchy in terms of scenes they only pit fall that jumped to mind for newer users is when unloading scenes understanding how Unity cleans that up e.g. what gets destroyed and when

Even if you tried to be supper man and not only handle networking but also scene management for 80% of the user base your going to get it wrong. I know you assume everyone but a 'power user' is using syncrionious single scene loading but that just isn't the case. We have a lot smaller community than yours but scene management is a common topic even with new day 1 Unity users. Really I think its far more common to see that behaviour with users that came from earlier versions of Unity or otherwise are thinking in terms of 'levels' or 'pages'.

Setting all of that aside and focusing on a solution
Assuming your not doing something crazy like having the Scene Management aspect handle spawn/despawn then why is it a problem to simply test for null and drive on with life if its not there?

**Comment by uweenukr** [comment]
I have some ideas on how to go about making this more flexible and open. Before I do that do you have any specific changes you could describe?

**Comment by JamesMcGhee** [comment]
My main concern is that its not forced
I really cant think of a situation where I would want my network tooling to be controlling my scenes and so I really dont want to have to fight my network tooling to stop it from messing with my scenes.

Making scene management an optional componenet all for that, would even be happy to help design and implament variations for different scene approches but it needs to be an optional componenet not an expected/required one

**Comment by uweenukr** [comment]
Its worth noting that Mirage does not control all scene changes. You can still use the normal Unity.SceneManager. The reason for using the NetworkSceneManager would be loading up up a scene with network stuff in it and also likely wanting to communicate that content load to the client.

That aside it would be cool to not have to have a running NetworkSceneManager for those who want to do that.
