### ISSUE TITLE
DontDestroyOnLoad being forced

### ISSUE THREAD

**Issue by JamesMcGhee** [MirageNet/Mirage#587]
**Please explain the suggested feature in detail.**
NetworkSceneManager ... which IMO isn't needed at all in a networking tool is forcing DontDestroyOnLoad note that this moves the GameObject to a hidden scene at run time changing the higharchy of GameObjects ... please do not do this unless the developer asks for it

**How exactly does this keep you from releasing your game right now?**
We dont allow DontDestroyOnLoad in any of our projects

**Can you suggest a possible solution?**
Simply dont do it ... if you feel you need to give people a short cut to do such a thing then give them a boolean they can toggle on and off but certently never force it

**Additional context**

**Comment by dragonslaya84** [comment]
If you don't use DontDestroyOnLoad then every scene change you need to get the NetworkSceneManager and load it to mirror network scripts. I dont feel that not using is bad idea constantly have to reset and check for the NetworkSceneManager each scene change is generally a bad idea.

**Comment by uweenukr** [comment]
If you remove DDOL and do a normal unity scene change. How do you prevent the entire network from being destroyed? As it's parent GO would be.

That is why it's currently DDOL. If a better solution exists I'd be happy to try it

**Comment by JamesMcGhee** [comment]
Better solution

public bool DontDestroyOnLoad = true

As every other asset with a similar argument does

second, load additivly

We and quite a few at this point have the first scene persist ... here is a quick example of a typical project we work on in terms of scenes and when they load/unload ... note the # is the build index for simplicty sake

0 = bootstrap or start up ... this contians all the system level bits, the loading screen, error dialogs, dev consoles, main camera, listener, etc.
It performs validation and assuming all is right in the world it will load #1
Note that 0 is never unloaded so since Network Manager and the other bits would live here they are never unloaded.

1 = menu or title, this is the first real interactive scene of the game, its a bit heavier so you dont want it being your 0 it will liekly have some audio playing maybe a 3D scene set up for with some spiffy lighting and so on ... so ya not good for index 0 ... this scene has the UI the user would use to launch into the rest of the game or exit out. When the user goes into another scene from here they unload 1 ... note 0 is never unloaded

2+n = all the rest of your game. This depends a lot on the nature of your game as to what it will be, how many there will be, which is active when and why, etc.

**Comment by JamesMcGhee** [comment]
> If you don't use DontDestroyOnLoad then every scene change you need to get the NetworkSceneManager and load it to mirror network scripts. I dont feel that not using is bad idea constantly have to reset and check for the NetworkSceneManager each scene change is generally a bad idea.

No need to reset, no need it would be destroyed
Scenes can persist as I outlined in my previous post

And with anything your going to use at run time set a reference on something you can get to easily without performing a lookup. There are loads of ways of doing that we tend to use ScriptableObjects to create "GameSettings" or similar that gets all the references we need at run time and since its a SO it can be referenced cross scene at dev time.

**Comment by uweenukr** [comment]
So you keep the initial scene and do everything else as additive?

**Comment by JamesMcGhee** [comment]
Yep that is our usual flow and we see more and more projects we work with do this

Small wall of text to help spell it out in detail some of the things we do and see done with clients we support and why do not destroy on load gets in the way of this.

The "bootstrap" scene idea which is what we call it does a lot more than just keep managers alive without donot destroy on load

its also the home of your loading screen main camera, error dialog, boot up validation checks, etc.

this makes working with Cinamachine easy since 1 camera in the bootstrap virtuals everywhere else

this gives you a dialog that is always on top, uneffeected by scene load/unload and can be used for system level events e.g. an error dialog but also for things like announcements and what not

The loading screen being here means iits un effected by load/unload obviously a good thing, also means you can do a lot more with your loading screen such as show 3D objects that animate or even mini-games if you really wanted to point is it lives in a scene of its own, that doens't need to load since it loaded on start and isn't effected by other scene loads/unloads

Validation checks these are key especially if your working with another platform like PlayFab, Steam, GoG, Epic, etc. you need to make sure your APIs are up and ready if not notify the user and handle it gracefuly which what gracefully means differs from game to game some accept that you might run wihtout the API and so they disable game systems that depend on it and drive on... others requrie the API so they tell you whats wrong, maybe they try to close and relaunch from the platoform (steam does this out of the box) or maybe they just let you know they need the platform up and then close either way ... validation it should be dont before you load your game proper so bootstrap scene is ideal for it

Bootstrap scens are made to be as light as possible, so they will load faster than even a title scene which is usually meant to be flashy ... this means you can show splash screens or just your loading screen while you load what could be a full on 3D scene as your title scene ... if you load that tile as scene 0 then your inital load will take a few seconds and for those seconds the PC is unresponsive showing a black screen or just a locked up view of the desktop .. not as smooth as a loading screne and if something goes on the user is unsure ... is just taking a long time to load or is it hung up

Point is having that ultralight bootstrap scene at the start that never goes away and is the home of your system level bits is realy useful. having a scene management flow that understnads 0 = bootstrap, 1= title is also supper useful since it helps with scene clean up where 2+ are game scenes. 
THere are other structures of course ... where soem number of scenes are different title scens so you load 

0 then 1 then pick some title scene to be your prities so end up on menu with at least 3 scens loaded. My point here is there is a lot you can do with additive scene loading and maintaining your 0 scene all the time and its easy to do, easy to manage not something only a 'power user' does but something that means dontdestroy on lead gets in the way with as it mucks with what gameobjects are in what scene.

Now I will say another model we see a lot is where they have a bootstrap scene and they simply mark everything in it as donot destroy on load. The issue here is that now none of your objects in that boostrap can instantiate any gameobjects since if they do that gameobject will end up in whatever scene is active at the time which who knows what that is .. you could then parent the instantiated thing to something that was in your bootstrap but that is a couple extra steps that you could have avoided by simply having a donot destroy on load mark in there and leaving your bootstrap loaded all the time

You might ask why you would wnat to instantiate something in that scene ... usually its for a fancy loading screen or similar. When you go into a load event you set 0 as active this means objects spawned go into it. Now you can load 3D objects or even simple games there and all is well.
You load your next scene but dont let it activate on its own, when it hits 90% that meanst its ready to be activated ... let your user exit the loading sequince nicely .. they may be reading a tip, some lore or playing a minigame so maybe arn't ready to play yet ... maybe they just ran to the bathroom so arn't ther eto play e.g. a "Press X to start" in yoru loading screen when its ready ... I know you have seen that in a console game or 2.
Now when you do that you clean up your bootstrap if needed and set your new scene active .. smooth transition, player has control no flicker, no stutter nothing complicated just manually controlling your loading sequicence which is no more complicated than making maybe 3 calls to UnityEngine.SceneManagement.SceneManger

Core all of that will break to hell and back if you have your network trying to manage your scenes and if you have do not destroy in the mix you cant assume where objects are as easily ... can still be done but its not as easy

**Comment by phodoval** [comment]
@uweenukr added the boolean in #596. Closing.

**Comment by uweenukr** [comment]
The 'bootstrap scene' is how I do things in my game also. Your comment about trying to sort which scene an object is in is the biggest factor that keeps me from wanting to support multiple nested active scenes (nested lobbies). It seems like a nightmare to manage.

**Comment by dragonslaya84** [comment]
Everyone has there own way of doing things. I think good making it bool i guess but i can speak for myself i dont use the whole keep one scene for all things you need and load everything else in separate. That in itself works but can br major problem even for power users. Whether you use do not destroy on load or decide go the additive scene route they are bascially the same thing. One is done through scene other is done through code. I mean you have samr amount of control. The dony destroy objects go to a separate scene which if you are using that dony destroy on load option you know that and plan to use it that way and to me is exactly same as using dedicated scene. They both are separate and do the exact samething keep objects you want to persistent. You load your other scenes additively. In this instance using sont destroy unity takes care of managing it abit and i dont need to and can use regualt scene loading versus additve but both end up coming around to same principal in the end.

**Comment by JamesMcGhee** [comment]
> Everyone has there own way of doing things. I think good making it bool i guess but i can speak for myself i dont use the whole keep one scene for all things you need and load everything else in separate. That in itself works but can be major problem even for power users. Whether you use do not destroy on load or decide go the additive scene route they are bascially the same thing. One is done through scene other is done through code. I mean you have samr amount of control. The dony destroy objects go to a separate scene which if you are using that dony destroy on load option you know that and plan to use it that way and to me is exactly same as using dedicated scene. They both are separate and do the exact samething keep objects you want to persistent. You load your other scenes additively. In this instance using sont destroy unity takes care of managing it abit and i dont need to and can use regualt scene loading versus additve but both end up coming around to same principal in the end.

Yes any of the options can work
My main request was that its an option

As to why we use the approch we do is you can set a scene active by name or index ... the hidden scene Do not destroy has no idex and not sure if you can find it by name or even see it in the list of loaded scenes ... not sure on that though never tried ... just so much easier to say SceneManager.SetActiveScene(0); or whatever the exsact call is dont recall :)

And we dont put all objects there just "system" level things I guess you could say we treate scenes like levels of scope. Bootstrap is effectivly the "system" level so it persists allways, other scenes may come and go and why they come and go has nothing to do with the state of the network

**Comment by uweenukr** [comment]
The option is why I liked this change. It still provides a foundation for users but does not prevent them from making choices. Flexibility will always win with me.
