### ISSUE TITLE
Changelog.md has no meta file

### ISSUE THREAD

**Issue by James-Frowen** [MirageNet/Mirage#624]
**Describe the bug**
error: 
![screenshot of error](https://cdn.discordapp.com/attachments/810193226476421191/812754099442286662/unknown.png)

**To Reproduce**
1. Import from package manager
2. See error

**Comment by phodoval** [comment]
This is specific for SteamyFaceNG and has been fixed a couple of days ago. If you find any other issues with the transport, please report them on its repo directly.
