### ISSUE TITLE
Player does not spawn when Listening is false

### ISSUE THREAD

**Issue by James-Frowen** [MirageNet/Mirage#680]
**Describe the bug**
`NetworkServer.Listening = false` seems to break other features

Player does not spawn when Listening = false

**To Reproduce**
1. Open basic example
2. Change `Listening` checkbox to false
3. Start host mode
4. See that player does not spawn

**Expected behavior**
host mode should work normally when `Listening` is false

**Desktop (please complete the following information):**
* Mirage branch: v74

**Comment by uweenukr** [comment]
There is currently no way to go from Listening=false to Listening=true without restarting the network. It is only ever used in ListenAsync(). We need a different implementation that can be toggled. You may want to stop listening once the game starts for example.
