### ISSUE TITLE
LogSettings is broken

### ISSUE THREAD

**Issue by Hertzole** [MirageNet/Mirage#683]
**Describe the bug**
The LogSettings component just doesn't work most of the time. It's very frustrating to use as it keeps changing log levels for classes seemingly randomly. Changing them manually usually results in them being reset. Sometimes it even changes seemingly randomly without any input.

**To Reproduce**
It's hard to reproduce as it's very random. Just move around the log settings and enter play mode and it should happen.

**Expected behavior**
They should remain the same in the project, on prefabs, in scenes, everything. Just like every other serialized values. They should not randomly change when switching play mode.

**Desktop (please complete the following information):**
* OS: Windows 10 64-bit
* Build target: Windows
* Unity version: 2020.2
* Mirage version: 74.0.0

**Comment by James-Frowen** [comment]
It seems like the Log settings are stored in both EditorPrefs and the component, this could be what is causing them to go out of sync

**Comment by Hertzole** [comment]
Not only are they not saved properly, the order changes randomly from time to time. This keeps messing with source control.
