### ISSUE TITLE
Sync Settings doesn't appear with a custom editor

### ISSUE THREAD

**Issue by PourrezJ** [MirageNet/Mirage#718]
**Describe the bug**
If you use a [SyncVar] custom attribute in one of the class and you use a custom editor with, the 
sync settings side doesn't appear at the bottom.

**Repro project**
https://1drv.ms/u/s!AsPgjMI5fds-gbxw4rf0KF1A-zdKdA?e=G71xlz

**To Reproduce**
1. Open the attached project 'Mirage'
2. Click on 'GameObject' on sample scene
3. Scroll down to the compoment 'MyObject'

**Expected behavior**
The sync var settings

**Screenshots**
https://prnt.sc/10su1ur

**Desktop:**
* OS: Windows
* Unity version: 2020.3.0f1
* Mirage version: 81.0.2

**Comment by uweenukr** [comment]
Is your custom class of type NetworkBehaviour? The existing editor script that applies SyncSettings is only for that type or its derivatives.

I am unable to easily access the repro project as it requires signing into OneDrive.

**Comment by PourrezJ** [comment]
Yes of course, he is a child of NetworkBehaviour.

https://mega.nz/file/hAo2nBjT#AWCAnQ5zHHBXB97tvVcubiu_SwJ4SogWhVSih4ILlQI

**Comment by uweenukr** [comment]
Is this what you are trying to do?

![image](https://user-images.githubusercontent.com/1385108/112642657-e7d8be00-8e19-11eb-9fd1-2d3b6db975a1.png)


If so then do this:
`public class MyObjectEditor : NetworkBehaviourInspector`

**Comment by PourrezJ** [comment]
Oh no I had not seen, thank you
