### ISSUE TITLE
Using Mirage in asmdef also requires reference to UniTask asmdef

### ISSUE THREAD

**Issue by James-Frowen** [MirageNet/Mirage#735]
**Please explain the suggested feature in detail.**
In order to use Mirage Client or Server you must also have reference to UniTask asmdef. Needing to add Mirage's dependencies to reference to use Mirage is a pain. 

**How exactly does this keep you from releasing your game right now?**
This slows down creating games, causing 

**Can you suggest a possible solution?**
Add Public methods that dont require UniTask 

*This is a minor issue, but is a pain point while converting projects to mirage*

**Comment by vladqwerty435** [comment]
or completely remove UniTasks from Mirage

**Comment by James-Frowen** [comment]
Client and server methods no longer use UniTask
