### ISSUE TITLE
members missing from Mirror Migration guide

### ISSUE THREAD

**Issue by James-Frowen** [MirageNet/Mirage#740]
List of member that are in mirror but have been changed or removed in mirage. These items should be added to https://github.com/MirageNet/Mirage/blob/master/doc/Articles/Guides/MirrorMigration.md

**NetworkManager**
| Mirror                    | Mirage   | notes  |
|---------------------------------|---|--- 
| override OnStartClient          |   |   |
| override OnStopClient           |   |   |
| field autoStartServerBuild      |  HeadlessAutoStart | starts server when null graphicsDeviceType  |
| method ConfigureServerFrameRate |  HeadlessFrameLimiter | Sets frame rate when null graphicsDeviceType |
| field _networkAddress           |   |   |
| field mode (NetworkManagerMode) |   |   |

**Comment by uweenukr** [comment]
OnStartClient and OnStopClient got lost at some point likely on accident. I can add them back if we think its useful.
