### ISSUE TITLE
SyncList dont use Header attribute

### ISSUE THREAD

**Issue by James-Frowen** [MirageNet/Mirage#753]
**Describe the bug**
Headers arn't drawn when they are used on Synclists

**Screenshots**
![](https://cdn.discordapp.com/attachments/809535065054642256/826926955085037588/unknown.png)
![](https://cdn.discordapp.com/attachments/809535065054642256/826923166723080242/unknown.png)

**Additional context**
Synclists are drawn using the custom editor for Networkbehaviour, this will need to add header if a synclist has the attribute.

The same issue might apply to SpaceAttribute too

**Comment by uweenukr** [comment]
I don't think it's unique to SyncList. I'm pretty sure it does that for all Mirage woven types
