### ISSUE TITLE
Awake is not called in NetworkSceneChecker on server

### ISSUE THREAD

**Issue by nattawitta** [MirageNet/Mirage#754]
**Describe the bug**
Awake is not called in NetworkSceneChecker on server which will cause error KeyNotFoundException whenever sceneCheckerObjects[currentScene] is used in the script.

**To Reproduce**
1. Add NetworkSceneChecker script in player prefab
2. Spawn player on server
3. See error 
Or you can check MultipleAdditiveScenes sample. This sample is broken.

**Desktop (please complete the following information):**
* OS: Windows 10
* Build target: PC Standalone
* Unity version: 2020.2.1f1
* Mirage version: 80.0.1

**Comment by James-Frowen** [comment]
seems to be caused by the `Server` attribute 
![image](https://user-images.githubusercontent.com/23101891/113298523-da2ca800-92f3-11eb-8c7f-d1b3413bca26.png)
