### ISSUE TITLE
Add protected methods to NetworkAuthenticator for invoking events

### ISSUE THREAD

**Issue by Soren025** [MirageNet/Mirage#784]
**Please explain the suggested feature in detail.**
It is quite simple. Currently implementing `NetworkAuthenticator` requires the use of an obscure C# feature that I didn't even know what a thing until I ran out of other things to try when figuring out why mine wasn't working. (see image below)

`NetworkAuthenticator` methods `OnServerAuthenticate` and `OnClientAuthenticate` are the only ways to invoke the events in the base class to finalize authentication, yet they are what gets invoked for initializing messages for a `INetworkPlayer` forcing you to override them. This requires you to invoke the base method logic using `base.` on the above mentioned methods from outside said methods which I feel is unintuitive and confusing.

This stumped me for quite a while until I realized what was actually happening. I learned java originally and over there you couldn't directly invoke the base implementation of a overridden method. So it never even occurred to me that it was a thing you were able to do.

**How exactly does this keep you from releasing your game right now?**
Not anymore now that I learned the obscure C# involved, but it did derail development for a good 3-4 hours.

**Can you suggest a possible solution?**

Add non virtual protected methods to invoke the events instead of relying on invoking the `base.` of methods you are likely overriding.

**Additional context**
As a fun side note, remove the `base.` on line 66 of `BasicAuthenticator` and it will no longer work.

![Example of obscure C# feature](https://puu.sh/HzyXH/0d28ab8f25.png)

**Comment by Lymdun** [comment]
Fixed by #827
